### PR TITLE
Bug/mirrored instances

### PR DESCRIPTION
**Pull request by jimfoltz**
Correct the exported vertex order (winding) for flipped instances.

### CODE REVIEW

**Comment by jimfoltz** [comment]
I found a model[1] where the exporter fails to catch some mirrored, nested instances.

In the following image taken from NetFabb Basic. Image 1 is the our current master branch (ceb6dcf). Image 2 is with the 1st attempt at mirroring detection (1bf7ad0), and Image 3 is with this latest pull request (5927099).


[1] https://3dwarehouse.sketchup.com/model.html?id=fd16cf692a4d8ec7697d7f9718010293

**Comment by jimfoltz** [comment]
I found this helpful: http://math.stackexchange.com/a/184479

**Comment by thomthom** [comment]
Hmm... so in the third, is it correct then?

**Comment by jimfoltz** [comment]
Yes, the third. Netfabb colors back faces red. If you examine the sketchup model, the red areas in the first image correspond to instances in the model. The instances are likely flipped, but I am not sure how to tell that from Sketchup.

**Comment by thomthom** [comment]
Maybe this helps? http://stackoverflow.com/a/17982272

**Comment by thomthom** [comment]
Not by themselves AFAIK - you need context. Someone contributed a really nice and fast algorithm to detect internal and reversed faces for Solid Inspector a couple of weeks ago - I've implemented it in SI 2.2. https://bitbucket.org/thomthom/solid-inspector/src/1aeb992d5087b96e8fcc148d40ed728ddb0d066d/src/tt_solid_inspector2/shell.rb?at=2.2

Though I'm not sure if that'll help for mirrored instances when we export - don't have just need to keep track of whether an instance if flipped?

**Pull request merged**
